services:
  asr:
    build: ./asr
    container_name: asr-fw
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ASR_MODEL=small            # tiny/base/small/medium
      - ASR_DEVICE=cuda
      - ASR_COMPUTE_TYPE=int8_float16
    ports:
      - "7010:7010"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  router:
    build: ./router
    container_name: translator-router
    depends_on: [asr]
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"
    environment:
      - ASR_URL=http://127.0.0.1:7010
      - RIVA_ADDR=127.0.0.1:50051
      - A_IN=headset0_in
      - A_OUT=headset0_out
      - B_IN=headset1_in
      - B_OUT=headset1_out
      - A_SRC=es
      - A_TGT=en
      - B_SRC=en
      - B_TGT=es
      - VOICE_EN=English-US.Male-Neutral
      - VOICE_ES=Spanish-US.Female-1
      - SAMPLE_RATE=16000
      - FRAME_MS=20
      - BURST_MIN_MS=300
      - BURST_MAX_MS=600
