services:
  asr-trt:
    build: ./asr-trt
    container_name: asr-trt
    runtime: nvidia
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TRT_MODEL_SIZE=small
      - TRT_COMPUTE=int8
      - SAMPLE_RATE=16000
      - CACHE_DIR=/cache
    volumes:
      - ./asr-cache:/cache        # <-- persist TRT engine
    ports:
      - "7001:7001"

  router:
    build: ./router
    container_name: translator-router
    depends_on:
      - asr-trt
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"
    environment:
      - ASR_URL=http://127.0.0.1:7001
      - MT_URL=http://127.0.0.1:7010      # your local CT2 MT service
      - RIVA_ADDR=127.0.0.1:50051         # your running Riva TTS

      - A_IN=plughw:0,0
      - A_OUT=plughw:0,0
      - B_IN=plughw:1,0
      - B_OUT=plughw:1,0

      - SAMPLE_RATE=16000
      - FRAME_MS=20
      - BURST_MIN_MS=300
      - BURST_MAX_MS=600

      - VOICE_EN=English-US.Female-1
      - VOICE_ES=Spanish-US.Female-1
