services:
  asr-trt:
    build: ./asr-trt
    container_name: asr-trt
    runtime: nvidia
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SAMPLE_RATE=16000
      - MODEL_NAME=small
      - ENGINE_DIR=/engines/small
      - DEFAULT_LANG=           # leave empty to auto, or set "en"/"es"
    volumes:
      - /opt/whisper_trt/engines/small:/engines/small:ro
      # If you need to import your repo directly:
      # - /home/translator/whisper_trt:/opt/whisper_trt:ro
    ports:
      - "7001:7001"

  router:
    build: ./router
    container_name: translator-router
    depends_on: [asr-trt]
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"
    environment:
      # ASR points to TRT shim
      - ASR_URL=http://127.0.0.1:7001
      # MT points to your **local systemd** MT server (already on :7010)
      - MT_URL=http://127.0.0.1:7010
      # Riva quickstart you already run (gRPC)
      - RIVA_ADDR=127.0.0.1:50051

      # Audio
      - A_IN=plughw:0,0
      - A_OUT=plughw:0,0
      - B_IN=plughw:1,0
      - B_OUT=plughw:1,0

      # Router behavior
      - SAMPLE_RATE=16000
      - FRAME_MS=20
      - BURST_MIN_MS=300
      - BURST_MAX_MS=600

      # Voices (match your Riva list)
      - VOICE_EN=English-US.Female-1
      - VOICE_ES=Spanish-US.Female-1
