services:
  router:
    build: ./router
    container_name: translator-router
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"
    environment:
      # Endpoints
      - RIVA_ADDR=${RIVA_ADDR:-127.0.0.1:50051}
      - MT_ENDPOINT=${MT_ENDPOINT:-http://127.0.0.1:7010/mt}

      # Audio (defaults use dsnoop for capture, plughw for playback)
      - A_IN=${A_IN:-dsnoop:CARD=Audio,DEV=0}
      - A_OUT=${A_OUT:-plughw:CARD=Audio,DEV=0}
      - B_IN=${B_IN:-dsnoop:CARD=Audio_1,DEV=0}
      - B_OUT=${B_OUT:-plughw:CARD=Audio_1,DEV=0}

      # Directions
      - A_SRC=${A_SRC:-es}
      - A_TGT=${A_TGT:-en}
      - B_SRC=${B_SRC:-en}
      - B_TGT=${B_TGT:-es}

      # Voices
      - VOICE_EN=${VOICE_EN:-English-US.Female-1}
      - VOICE_ES=${VOICE_ES:-Spanish-US.Female-1}

      # Timing / audio params
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}
      - FRAME_MS=${FRAME_MS:-20}
      - BURST_MIN_MS=${BURST_MIN_MS:-300}
      - BURST_MAX_MS=${BURST_MAX_MS:-600}
      - VAD_LEVEL=${VAD_LEVEL:-2}
      - HANGOVER_MS=${HANGOVER_MS:-150}
      - HARD_TIMEOUT_MS=${HARD_TIMEOUT_MS:-2500}
      - DEBUG=${DEBUG:-0}
