services:
  asr:
    build: ./asr-fastwhisper
    container_name: asr-fastwhisper
    runtime: nvidia
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - FW_MODEL=small
      - FW_DEVICE=cuda
      - FW_COMPUTE_TYPE=float16
      - SAMPLE_RATE=16000
    ports:
      - "7001:7001"

  router:
    build: ./router
    container_name: translator-router
    depends_on:
      - asr
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"
    environment:
      - ASR_URL=http://127.0.0.1:7001
      - MT_URL=http://127.0.0.1:7010           # your local MT service (already running)
      - RIVA_ADDR=127.0.0.1:50051              # your Riva quickstart

      # Audio
      - A_IN=plughw:0,0
      - A_OUT=plughw:0,0
      - B_IN=plughw:1,0
      - B_OUT=plughw:1,0

      # Router behavior
      - SAMPLE_RATE=16000
      - FRAME_MS=20
      - BURST_MIN_MS=300
      - BURST_MAX_MS=600

      # Voices
      - VOICE_EN=English-US.Female-1
      - VOICE_ES=Spanish-US.Female-1
