services:
  canary:
    build: ./canary-ast
    container_name: canary-ast
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TRANSFORMERS_NO_TORCHVISION=1     # keep this for safety
      # Later, when you want real Canary AST instead of FW fallback:
      # - CANARY_MODEL_ID=nvidia/canary-1b-v2
    ports:
      - "7000:7000"
  router:
    build: ./router
    container_name: translator-router
    depends_on: [canary]
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true  # For testing
    volumes:
      # Mount the ALSA configuration
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"
    environment:
      - CANARY_URL=http://127.0.0.1:7000/ast
      - RIVA_ADDR=127.0.0.1:50051
      # Use the named devices from .asoundrc
      - A_IN=plughw:0,0
      - A_OUT=plughw:0,0
      - B_IN=plughw:1,0
      - B_OUT=plughw:1,0
      - A_SRC=es
      - A_TGT=en
      - B_SRC=en
      - B_TGT=es
      - RIVA_VOICE_A=English-US.Female-1
      - RIVA_VOICE_B=Spanish-US.Female-1
      - FRAME_MS=20
      - BURST_MIN_MS=300
      - BURST_MAX_MS=600
      - SAMPLE_RATE=16000
