services:
  router:
    build: ./router
    container_name: translator-router
    # access host Riva (gRPC :50051) and your local MT (:7010)
    network_mode: "host"

    # pass ALSA devices for capture/playback
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"

    environment:
      # Endpoints
      - RIVA_ADDR=127.0.0.1:50051       # your on-device Riva
      - MT_URL=http://127.0.0.1:7010    # your local MT service

      # Audio (adjust to your cards)
      - A_IN=plughw:0,0
      - A_OUT=plughw:0,0
      - B_IN=plughw:1,0
      - B_OUT=plughw:1,0

      # Directions: A speaks es->en, B speaks en->es (change as needed)
      - A_SRC=es
      - A_TGT=en
      - B_SRC=en
      - B_TGT=es

      # Voices available in your Riva
      - VOICE_EN=English-US.Female-1
      - VOICE_ES=Spanish-US.Female-1

      # Timing / audio params
      - SAMPLE_RATE=16000
      - FRAME_MS=20
      - BURST_MIN_MS=300
      - BURST_MAX_MS=600
      - VAD_LEVEL=2
