version: "3.8"

services:
  canary:
    build: ./canary-ast
    container_name: canary-ast
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # If/when you have a HF Canary model:
      # - CANARY_MODEL_ID=nvidia/canary-1b-v2
    ports:
      - "7000:7000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  router:
    build: ./router
    container_name: translator-router
    depends_on: [canary]
    network_mode: "host"              # talks to Riva on 127.0.0.1:50051
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"   # so friendly ALSA names work in container
    environment:
      - CANARY_URL=http://127.0.0.1:7000/ast
      - RIVA_ADDR=127.0.0.1:50051
      - A_IN=headset0_in
      - A_OUT=headset0_out
      - B_IN=headset1_in
      - B_OUT=headset1_out
      - A_SRC=es
      - A_TGT=en
      - B_SRC=en
      - B_TGT=es
      - RIVA_VOICE_A=English-US.Female-1   # from your Riva voice list
      - RIVA_VOICE_B=Spanish-US.Female-1   # from your Riva voice list
      - FRAME_MS=20
      - BURST_MIN_MS=300
      - BURST_MAX_MS=600
      - SAMPLE_RATE=16000
