services:
  canary:
    build: ./canary-ast
    container_name: canary-ast
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CANARY_MODEL_ID=nvidia/canary-1b-flash
      - SAMPLE_RATE=16000
    ports:
      - "7000:7000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


  router:
    build: ./router
    container_name: translator-router
    depends_on: [canary]
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - "${HOME}/.asoundrc:/root/.asoundrc:ro"
    environment:
      - CANARY_URL=http://127.0.0.1:7000/ast
      - RIVA_ADDR=127.0.0.1:50051
      - A_IN=plughw:0,0
      - A_OUT=plughw:0,0
      - B_IN=plughw:1,0
      - B_OUT=plughw:1,0
